apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blog-website
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: my-blog
  template:
    metadata:
      labels:
        app: my-blog
    spec:
      containers:
        - name: my-blog-website
          image: andywu11/my-blog
          ports:
            - containerPort: 80